// Action codes for audit_logs.action. REQ-AUDIT-002 lists the operations that must be recorded;
// this file is the single registry of the string codes used across the codebase so that
// /admin/audit filtering and future analysis have a stable, typo-proof vocabulary. Extend this
// object — never invent an ad-hoc string at the call site.
export const AUDIT_ACTIONS = {
  // Authentication (Phase 1)
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  INITIAL_SETUP_TOKEN_ISSUED: "INITIAL_SETUP_TOKEN_ISSUED",
  INITIAL_SETUP_COMPLETED: "INITIAL_SETUP_COMPLETED",
  INITIAL_SETUP_TOKEN_REJECTED: "INITIAL_SETUP_TOKEN_REJECTED",
  PASSWORD_RESET_APPROVED: "PASSWORD_RESET_APPROVED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PASSWORD_RESET_TOKEN_REJECTED: "PASSWORD_RESET_TOKEN_REJECTED",

  // Users / roles / stores (Phase 1)
  USER_REGISTERED: "USER_REGISTERED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_LOGIN_NAME_CHANGED: "USER_LOGIN_NAME_CHANGED",
  MEMBERSHIP_CREATED: "MEMBERSHIP_CREATED",
  ROLE_GRANTED: "ROLE_GRANTED",
  ROLE_REVOKED: "ROLE_REVOKED",
  MANAGER_SCOPE_GRANTED: "MANAGER_SCOPE_GRANTED",
  MANAGER_SCOPE_REVOKED: "MANAGER_SCOPE_REVOKED",

  // Periods (Phase 2)
  PERIOD_DEADLINE_SET: "PERIOD_DEADLINE_SET",
  PERIOD_EVENTS_CONFIRMED: "PERIOD_EVENTS_CONFIRMED",
  PERIOD_COLLECTION_OPENED: "PERIOD_COLLECTION_OPENED",
  PERIOD_COLLECTION_CLOSED: "PERIOD_COLLECTION_CLOSED",
  PERIOD_COLLECTION_REOPENED: "PERIOD_COLLECTION_REOPENED",
  PERIOD_TARGET_EXCLUDED: "PERIOD_TARGET_EXCLUDED",
  PERIOD_TARGET_REINCLUDED: "PERIOD_TARGET_REINCLUDED",

  // Events (Phase 2)
  EVENT_CREATED: "EVENT_CREATED",
  EVENT_UPDATED: "EVENT_UPDATED",
  EVENT_DISABLED: "EVENT_DISABLED",

  // Standard shifts / availability (Phase 3)
  STANDARD_SHIFT_UPDATED: "STANDARD_SHIFT_UPDATED",
  AVAILABILITY_DRAFT_SAVED: "AVAILABILITY_DRAFT_SAVED",
  AVAILABILITY_SUBMITTED: "AVAILABILITY_SUBMITTED",
  AVAILABILITY_LATE_SUBMITTED: "AVAILABILITY_LATE_SUBMITTED",
  AVAILABILITY_REOPENED: "AVAILABILITY_REOPENED",
  UNSUBMITTED_NOTIFICATION_GENERATED: "UNSUBMITTED_NOTIFICATION_GENERATED",

  // Scheduling / publication (Phase 4)
  CONFIRMED_SHIFT_SAVED: "CONFIRMED_SHIFT_SAVED",
  CONFIRMED_SHIFT_CANCELLED: "CONFIRMED_SHIFT_CANCELLED",
  SCHEDULING_CONFIRMED: "SCHEDULING_CONFIRMED",
  SHIFT_PUBLISHED: "SHIFT_PUBLISHED",
  POST_PUBLICATION_CHANGE: "POST_PUBLICATION_CHANGE",

  // CSV (Phase 5)
  CSV_IMPORT_UPLOADED: "CSV_IMPORT_UPLOADED",
  CSV_IMPORT_APPLIED: "CSV_IMPORT_APPLIED",
  CSV_IMPORT_CANCELLED: "CSV_IMPORT_CANCELLED",
  CSV_EXPORTED: "CSV_EXPORTED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
