flowchart TD
  A[currently/index.html] --> B[currently/shop/index.html]
  A --> C[currently/cast/index.html]
  A --> D[currently/recruit/index.html]
  A --> E[currently/planet-group/index.html]
  A --> F[currently/shop/*/menu/index.html]
  B --> G[currently/shop/shinjuku/index.html]
  B --> H[currently/shop/cybarshinjuku/index.html]
  B --> I[currently/shop/chocolat/index.html]
  B --> J[currently/shop/shandy/index.html]
  B --> K[currently/shop/melty/index.html]
  B --> L[currently/shop/bloody/index.html]
  B --> M[currently/shop/roysuga/index.html]
  B --> N[currently/shop/tweeny/index.html]
  B --> O[currently/shop/cybarbkk/index.html]
  B --> P[currently/shop/cybarbkk2/index.html]
  B --> Q[currently/shop/cybarlaos/index.html]
  G --> GA[currently/shop/shinjuku/menu/index.html]
  H --> HA[currently/shop/cybarshinjuku/menu/index.html]
  I --> IA[currently/shop/chocolat/menu/index.html]
  J --> JA[currently/shop/shandy/menu/index.html]
  K --> KA[currently/shop/melty/menu/index.html]
  L --> LA[currently/shop/bloody/menu/index.html]
  M --> MA[currently/shop/roysuga/menu/index.html]
  N --> NA[currently/shop/tweeny/menu/index.html]
  O --> OA[currently/shop/cybarbkk/menu/index.html]
  P --> PA[currently/shop/cybarbkk2/menu/index.html]
  Q --> QA[currently/shop/cybarlaos/menu/index.html]

  R[currently/index.html] --> S[currently/shop/index.html]
  R --> T[currently/cast/index.html]
  R --> U[currently/recruit/index.html]
  R --> V[currently/planet-group/index.html]
  R --> W[currently/shop/*/menu/index.html]
  S --> X[currently/shop/shinjuku/index.html]
  S --> Y[currently/shop/cybarshinjuku/index.html]
  S --> Z[currently/shop/chocolat/index.html]
  S --> AA[currently/shop/shandy/index.html]
  S --> AB[currently/shop/melty/index.html]
  S --> AC[currently/shop/bloody/index.html]
  S --> AD[currently/shop/roysuga/index.html]
  S --> AE[currently/shop/tweeny/index.html]
  S --> AF[currently/shop/cybarbkk/index.html]
  S --> AG[currently/shop/cybarbkk2/index.html]
  S --> AH[currently/shop/cybarlaos/index.html]
  X --> XA[currently/shop/shinjuku/menu/index.html]
  Y --> YA[currently/shop/cybarshinjuku/menu/index.html]
  Z --> ZA[currently/shop/chocolat/menu/index.html]
  AA --> AAA[currently/shop/shandy/menu/index.html]
  AB --> ABA[currently/shop/melty/menu/index.html]
  AC --> ACA[currently/shop/bloody/menu/index.html]
  AD --> ADA[currently/shop/roysuga/menu/index.html]
  AE --> AEA[currently/shop/tweeny/menu/index.html]
  AF --> AFA[currently/shop/cybarbkk/menu/index.html]
  AG --> AGA[currently/shop/cybarbkk2/menu/index.html]
  AH --> AHA[currently/shop/cybarlaos/menu/index.html]
